admins: zhaocy.dut@gmail.com 
project_dir: /path/to/dir/you/want/to/save/the/results
 
raw_fast5_fp1: /path/to/dir/fast5/files/1
raw_fast5_fp2: /path/to/dir/fast5/files/2/happens/when/no/prearrangment/on/local/computer/memory

## put these in your project_dir, will be our workdir for snakemake
barcodes_fp: barcodes.txt
genome_fp: GCF_000932055.fa
gene_fp: GCF_000932055.gff
short_reads_fp: short_reads_truseq

## helper scripts
basecalling_cmp_fp: $HOME/nanoflow/local/Basecalling-comparison
canu_genome_size: 4.3m
nanopolish_fp: $HOME/nanoflow/local/nanopolish
quast_yaml_fp: $HOME/nanoflow/quast.yaml
igv_prefs : {ENABLE_ANTIALIASING: true, NAME_PANEL_WIDTH: 360, SAM.MAX_VISIBLE_RANGE: 1000}
keep_unaligned: false

